Client.Subscribe("SpawnLocalPlayer", function(pLocal)
	pLocal:Subscribe("Possess", function(pPly, cChar)
        ONC.BaseHUD:CallEvent("ONC::ToggleCharacterCreator")
        Input.SetMouseEnabled(true)
        Input.SetInputEnabled(false)
        ONC.BaseHUD:BringToFront()

        ONC.BaseHUD:Subscribe("ONC::CreateCharacter", function(sFirstName, sLastName, sBirthDate)
            Events.CallRemote("ONC::SendCharacterInformation", sFirstName, sLastName, sBirthDate)
            Input.SetMouseEnabled(false)
            Input.SetInputEnabled(true)
        end)
    end)
end)